// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgac_FOsMm_kUmmBMKYuH2cyM1Pw9_YMM',
    appId: '1:1022855890141:web:4484421f875a950a74c734',
    messagingSenderId: '1022855890141',
    projectId: 'newsletter-66f48',
    authDomain: 'newsletter-66f48.firebaseapp.com',
    storageBucket: 'newsletter-66f48.firebasestorage.app',
    measurementId: 'G-27B7202THV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXa36M3cojYTPjSSSN_hEHintzyZNaI54',
    appId: '1:1022855890141:android:2b04bcdc4e43da8874c734',
    messagingSenderId: '1022855890141',
    projectId: 'newsletter-66f48',
    storageBucket: 'newsletter-66f48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDumV9OL3USybh0PoXyTY-DAQanrPD2Lz0',
    appId: '1:1022855890141:ios:6914c7082f989f1b74c734',
    messagingSenderId: '1022855890141',
    projectId: 'newsletter-66f48',
    storageBucket: 'newsletter-66f48.firebasestorage.app',
    iosBundleId: 'dev.caina.newsletter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDumV9OL3USybh0PoXyTY-DAQanrPD2Lz0',
    appId: '1:1022855890141:ios:6914c7082f989f1b74c734',
    messagingSenderId: '1022855890141',
    projectId: 'newsletter-66f48',
    storageBucket: 'newsletter-66f48.firebasestorage.app',
    iosBundleId: 'dev.caina.newsletter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgac_FOsMm_kUmmBMKYuH2cyM1Pw9_YMM',
    appId: '1:1022855890141:web:14b962a56b39551d74c734',
    messagingSenderId: '1022855890141',
    projectId: 'newsletter-66f48',
    authDomain: 'newsletter-66f48.firebaseapp.com',
    storageBucket: 'newsletter-66f48.firebasestorage.app',
    measurementId: 'G-4E023BBF6W',
  );
}
